#name of the project
name: flight fare predictor

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        env:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "flight-fare-prediction0" #App Name
          heroku_email: "sanketmaheshwari96@gmail.com"